/** Static defaults used only during database seeding. Runtime reads from DB. */

export const DEFAULT_LANGUAGES = [
  "Hindi",
  "English",
  "Marathi",
  "Tamil",
  "Telugu",
  "Kannada",
  "Bengali",
  "Gujarati",
  "Punjabi",
  "Malayalam",
];

export const DEFAULT_SKILLS_BY_CATEGORY: Record<string, string[]> = {
  plumber: [
    "Pipe repair",
    "Leak detection",
    "Bathroom fitting",
    "Water heater installation",
    "Tap & faucet repair",
    "Drain cleaning",
    "Toilet repair",
    "Kitchen plumbing",
  ],
  electrician: [
    "Home wiring",
    "Switchboard repair",
    "Fan installation",
    "Light fixture installation",
    "MCB & fuse repair",
    "Appliance wiring",
    "Smart home setup",
    "Electrical safety check",
  ],
  carpenter: [
    "Furniture repair",
    "Custom woodwork",
    "Door & window fitting",
    "Modular kitchen",
    "Wardrobe installation",
    "Bed & table repair",
    "Polishing & finishing",
  ],
  "ac-technician": [
    "AC installation",
    "AC servicing",
    "Gas refill",
    "Cooling system repair",
    "Duct cleaning",
    "Split AC repair",
  ],
  cleaner: [
    "Deep cleaning",
    "Kitchen cleaning",
    "Bathroom cleaning",
    "Sofa & carpet cleaning",
    "Move-in / move-out cleaning",
    "Office cleaning",
    "Post-construction cleaning",
  ],
  tutor: [
    "Mathematics",
    "Science",
    "English",
    "Hindi",
    "Competitive exam prep",
    "Computer basics",
    "Music",
    "Art & craft",
  ],
  "home-chef": [
    "Daily meals",
    "Party catering",
    "Vegetarian cooking",
    "Non-vegetarian cooking",
    "Jain food",
    "Baking",
    "Regional cuisine",
  ],
  driver: [
    "City driving",
    "Outstation trips",
    "Airport pickup",
    "Chauffeur service",
    "School pickup",
  ],
  childcare: [
    "Babysitting",
    "Full-day nanny",
    "Newborn care",
    "Homework help",
    "Play & activities",
  ],
  photographer: [
    "Event photography",
    "Portrait photography",
    "Wedding photography",
    "Product photography",
    "Video coverage",
  ],
  "makeup-artist": [
    "Bridal makeup",
    "Party makeup",
    "Engagement makeup",
    "Hair styling",
    "Saree draping",
  ],
  "fitness-trainer": [
    "Personal training",
    "Yoga",
    "Weight loss coaching",
    "Strength training",
    "Home workouts",
  ],
  "elder-care": [
    "Companionship",
    "Medication reminders",
    "Mobility assistance",
    "Meal assistance",
    "Daily errands",
  ],
  delivery: [
    "Local delivery",
    "Courier pickup",
    "Grocery delivery",
    "Document delivery",
  ],
};

export const DEFAULT_COMMON_SKILLS = [
  "Customer service",
  "Punctual & reliable",
  "Emergency service",
  "Weekend availability",
];

export const DEFAULT_SERVICE_AREAS_BY_CITY: Record<string, string[]> = {
  Mumbai: [
    "Andheri East",
    "Andheri West",
    "Bandra",
    "Borivali",
    "Chembur",
    "Colaba",
    "Dadar",
    "Goregaon",
    "Juhu",
    "Kandivali",
    "Malad",
    "Mulund",
    "Powai",
    "Thane",
    "Vile Parle",
    "Worli",
  ],
  Delhi: [
    "Connaught Place",
    "Dwarka",
    "Karol Bagh",
    "Lajpat Nagar",
    "Nehru Place",
    "Rohini",
    "Saket",
    "South Delhi",
    "Vasant Kunj",
    "Noida",
    "Gurgaon",
  ],
  Bangalore: [
    "Indiranagar",
    "Koramangala",
    "Whitefield",
    "Electronic City",
    "HSR Layout",
    "Jayanagar",
    "Marathahalli",
    "MG Road",
    "Hebbal",
    "Yelahanka",
  ],
  Hyderabad: [
    "Banjara Hills",
    "Gachibowli",
    "Hitech City",
    "Jubilee Hills",
    "Kukatpally",
    "Madhapur",
    "Secunderabad",
  ],
  Chennai: [
    "Adyar",
    "Anna Nagar",
    "ECR",
    "OMR",
    "Porur",
    "T Nagar",
    "Velachery",
  ],
  Pune: [
    "Baner",
    "Hinjewadi",
    "Kharadi",
    "Koregaon Park",
    "Pimple Saudagar",
    "Viman Nagar",
    "Wakad",
  ],
};
