#!/usr/bin/env bash
# Idempotent Cloud Agent setup for KaamSetu (Next.js + Prisma + PostgreSQL).
# Safe to run repeatedly; converges the VM to a ready-to-develop state.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

PG_VERSION="16"
PG_CLUSTER="main"

# 1. Ensure PostgreSQL is installed (default image does not ship it).
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  echo "Installing PostgreSQL ${PG_VERSION}..."
  sudo apt-get update -qq
  sudo apt-get install -y -qq postgresql postgresql-contrib
fi

# 2. Start the PostgreSQL cluster (idempotent).
sudo pg_ctlcluster "${PG_VERSION}" "${PG_CLUSTER}" start 2>/dev/null || true
for _ in $(seq 1 30); do
  if pg_isready -h localhost -q; then break; fi
  sleep 1
done

# 3. Ensure the postgres role password and the application database exist.
sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" >/dev/null
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='kaamsetu'" | grep -q 1; then
  sudo -u postgres createdb kaamsetu
fi

# 4. Ensure a local .env exists (never overwrite an existing one).
if [ ! -f .env ]; then
  echo "Creating .env from local defaults..."
  AUTH_SECRET="$(openssl rand -base64 32)"
  cat > .env <<EOF
# Local development environment (generated by .cursor/install.sh)
DATABASE_URL="postgresql://postgres:postgres@localhost:5432/kaamsetu"
AUTH_SECRET="${AUTH_SECRET}"
AUTH_URL="http://localhost:3000"

# Optional integrations — the app runs in demo/console mode when unset.
RAZORPAY_KEY_ID=""
RAZORPAY_KEY_SECRET=""
RESEND_API_KEY=""
EMAIL_FROM="KaamSetu <noreply@kaamsetu.com>"
MSG91_API_KEY=""
MSG91_SENDER_ID=""
MSG91_TEMPLATE_ID=""
CLOUDINARY_CLOUD_NAME=""
CLOUDINARY_API_KEY=""
CLOUDINARY_API_SECRET=""
CLOUDINARY_UPLOAD_PRESET=""
EOF
fi

# 5. Install dependencies (postinstall runs `prisma generate`).
npm ci

# 6. Sync the schema and seed demo data (both idempotent).
npm run db:push
npm run db:seed

echo "KaamSetu environment setup complete."
